config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [] do
    resources :orders, only: %i[index show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :carts, only: :show
  resources :products do
    collection do
      get :search
    end
  end

  resources :product_variations

  resources :line_items, only: %i[create destroy] do
    member do
      post :change_quantity
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :fake_users, only: %i[new create edit update] do
    resources :orders, only: %i[show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :categories, only: :show

  resources :product_favorites, only: %i[create destroy]

  # custom route to redirect user to the correct page
  # when they start an order and want to login after
  get 'login_before_new_order', to: 'orders#login_before_new'

  # route to the user profile page
  get 'dashboards', to: 'dashboards#dashboard'

  # route for product creation tool
  get 'product_creation', to: 'dashboards#product_creation_new'
  post 'product_creation', to: 'dashboards#product_creation_create'
  root to: 'products#index'

  # routes for info pages
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get 'returns_and_exchanges', to: 'pages#returns_and_exchanges'
  get 'shipping', to: 'pages#shipping'
  get 'faq', to: 'pages#faq'
  get 'about_us', to: 'pages#about_us'
  get 'covid_19', to: 'pages#covid_19'
  get 'wholesales', to: 'pages#wholesales'

  # route form doctor contact form
  post 'doctor_contact_form', to: 'doctors#doctor_contact_form'
end

app/models/fake_user.rb
class FakeUser < ApplicationRecord
  has_many :orders
  has_many :addresses, dependent: :destroy

  before_destroy :remove_orders_foreign_key

  validates :first_name, :last_name, :phone, :email, presence: true

  private

  # When we delete an user we want its orders not to be deleted
  # we need this callback to avoid foreign key constraint
  def remove_orders_foreign_key
    orders.each do |order|
      order.update(fake_user: nil)
    end
  end
end

app/controllers/fake_users_controller.rb
class FakeUsersController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @fake_user = FakeUser.new
    @address = Address.new
    @breadcrumb_contact_class = 'active'
    @breadcrumb_shipping_class = 'pending'
    @breadcrumb_review_class = @breadcrumb_confirm_class = 'pending hide-under-576'
  end

  def create
    @fake_user = FakeUser.new(fake_user_params)
    if @fake_user.save
      redirect_to new_fake_user_address_path(@fake_user)
    else
      render :new
    end
  end

  def edit
    # DRY
    @breadcrumb_contact_class = 'active'
    @breadcrumb_review_class = @breadcrumb_confirm_class = 'pending hide-under-576'

    @fake_user = FakeUser.find(params[:id])
  end

  def update
    @fake_user = FakeUser.find(params[:id])
    if @fake_user.update(fake_user_params)
      redirect_to new_fake_user_order_path(@fake_user)
    else
      render :edit
    end
  end

  private

  def fake_user_params
    params.require(:fake_user).permit(:first_name, :last_name, :email, :address, :phone)
  end
end

app/views/fake_users/edit.html.erb
<div class="container orders-funnel">
  <%= render 'shared/order_breadcrumb' %>
  <h1>INFORMACIÓN DE CONTACTO</h1>
  <br>
  <p>
    Ya tienes una cuenta? Porfavor <b><%= link_to 'CONECTARSE', login_before_new_order_path %></b> o <b><%= link_to 'CREAR CUENTA', new_user_registration_path %></b>
  </p>
  <p>O continuar sin creación de cuenta:</p>
  <%= simple_form_for @fake_user do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :first_name, label: false, placeholder: 'Nombre', class: 'form-control' %>
      </div>
      <div class="col-sm-6">
        <%= f.input :last_name, label: false, placeholder: 'Apellido', class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :email, label: false, placeholder: 'Email', class: 'form-control' %>
      </div>
      <div class="col-sm-6">
        <%= f.input :phone, label: false, placeholder: 'Teléfono', class: 'form-control' %>
      </div>
    </div>
    <%= f.button :submit, 'SEGUIR', class: 'btn btn-blue w-100' %>
  <% end %>
</div>

app/views/fake_users/new.html.erb
<div class="container orders-funnel">
  <%= render 'shared/order_breadcrumb' %>
  <h1>INFORMACIÓN DE CONTACTO</h1>
  <br>
  <p>
    Ya tienes una cuenta? Porfavor <b><%= link_to 'CONECTARSE', login_before_new_order_path %></b> o <b><%= link_to 'CREAR CUENTA', new_user_registration_path %></b>
  </p>
  <p>O continuar sin creación de cuenta:</p>
  <%= simple_form_for [@fake_user] do |f| %>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :first_name, label: false, placeholder: 'Nombre', class: 'form-control' %>
      </div>
      <div class="col-sm-6">
        <%= f.input :last_name, label: false, placeholder: 'Apellido', class: 'form-control' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <%= f.input :email, label: false, placeholder: 'Email', class: 'form-control' %>
      </div>
      <div class="col-sm-6">
        <%= f.input :phone, label: false, placeholder: 'Teléfono', class: 'form-control' %>
      </div>
    </div>
    <%= f.button :submit, 'SEGUIR', class: 'btn btn-blue w-100' %>
  <% end %>
</div>