config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [] do
    resources :orders, only: %i[index show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :carts, only: :show
  resources :products do
    collection do
      get :search
    end
  end

  resources :product_variations

  resources :line_items, only: %i[create destroy] do
    member do
      post :change_quantity
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :fake_users, only: %i[new create edit update] do
    resources :orders, only: %i[show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :categories, only: :show

  resources :product_favorites, only: %i[create destroy]

  # custom route to redirect user to the correct page
  # when they start an order and want to login after
  get 'login_before_new_order', to: 'orders#login_before_new'

  # route to the user profile page
  get 'dashboards', to: 'dashboards#dashboard'

  # route for product creation tool
  get 'product_creation', to: 'dashboards#product_creation_new'
  post 'product_creation', to: 'dashboards#product_creation_create'
  root to: 'products#index'

  # routes for info pages
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get 'returns_and_exchanges', to: 'pages#returns_and_exchanges'
  get 'shipping', to: 'pages#shipping'
  get 'faq', to: 'pages#faq'
  get 'about_us', to: 'pages#about_us'
  get 'covid_19', to: 'pages#covid_19'
  get 'wholesales', to: 'pages#wholesales'

  # route form doctor contact form
  post 'doctor_contact_form', to: 'doctors#doctor_contact_form'
end

app/views/shared/_atc_modal.html.erb
<div class="modal fade" id="atcModal" tabindex="-1" role="dialog" aria-labelledby="atcModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-body text-center">
        <% if params[:chosen_product] %>
          <b><%= params[:chosen_product]%></b> añadido a su carrito
        <% else %>
          <b><%= @product.name %></b> añadido a su carrito
        <% end %>
      </div>
      <div class="modal-footer text-center">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">SEGUIR COMPRANDO</button>
        <%= link_to "CARRITO", cart_path(@current_cart), class: "btn btn-primary" %>
      </div>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
</div>

app/views/shared/_carousel.html.erb
<section class="position-relative carousel-container">
  <div id="hp-carousel" class="carousel slide" data-ride="carousel">
    <div class="container">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <%= image_tag 'hp-banner2.png' %>
          <div class="carousel-caption d-md-block">
            <h2>PRODUCTOS<br>DE PROTECCIÓN<br>MEDICA</h2>
<!--             <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            <a href="#" class="btn btn-primary">Some Link</a> -->
          </div>
        </div>
        <div class="carousel-item">
          <%= image_tag 'hp-banner1.png' %>
          <div class="carousel-caption d-md-block">
            <h2>PRODUCTOS<br>DE PROTECCIÓN<br>MEDICA</h2>
<!--             <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
            <a href="#" class="btn btn-primary">Some Link</a> -->
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#hp-carousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#hp-carousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class="container">
      <div class="carousel-bottom-banner simple-flexbox">
        <%= image_tag 'watch.png' %>
        <span>ENTREGA DE TODOS LOS PEDIDOS EN 24 HORAS</span>
      </div>
    </div>
  </div>
</section>

app/views/shared/_carousel_doctors.html.erb
<div id="hp-carousel-doctor" class="carousel slide bg-yellow" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active" data-slide-id="1">
      <div class="d-flex h-100">
        <img src="https://picsum.photos/1000/250" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <div>
            <h3>DOCTORA 1</h3>
            <h3>NOMBRE</h3>
            <h3>APELLIDO</h3>
            <p>ESPECIALIDAD</p>
            <a type="button" class="btn btn-blue" data-toggle="modal" data-target="#contactFormDoctor"><%= inline_svg_tag('symbol.svg') %>HACER UNA CITA</a>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item" data-slide-id="2">
      <div class="d-flex h-100">
        <img src="https://picsum.photos/1000/250" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <div>
            <h3>DOCTORA 2</h3>
            <h3>NOMBRE</h3>
            <h3>APELLIDO</h3>
            <p>ESPECIALIDAD</p>
            <a type="button" class="btn btn-blue" data-toggle="modal" data-target="#contactFormDoctor"><%= inline_svg_tag('symbol.svg') %>HACER UNA CITA</a>
          </div>
        </div>
      </div>
    </div>
    <div class="carousel-item" data-slide-id="3">
      <div class="d-flex h-100">
        <img src="https://picsum.photos/1000/250" class="d-block" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <div>
            <h3>DOCTORA 3</h3>
            <h3>NOMBRE</h3>
            <h3>APELLIDO</h3>
            <p>ESPECIALIDAD</p>
            <a type="button" class="btn btn-blue" data-toggle="modal" data-target="#contactFormDoctor"><%= inline_svg_tag('symbol.svg') %>HACER UNA CITA</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <a class="carousel-control-prev" href="#hp-carousel-doctor" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#hp-carousel-doctor" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<div class="hp-carousel-doctors-grid-container bg-yellow">
  <div class="container hp-carousel-doctors-grid">
    <div class="hp-carousel-doctor-profile" data-slide-id="1">
      <img src="https://picsum.photos/300/300" class="d-block" alt="...">
      <a href="" class="active">
        <h3>DOCTORA 1</h3>
        <h3>NOMBRE</h3>
        <h3>APELLIDO</h3>
        <p>ESPECIALIDAD</p>
      </a>
    </div>
    <div class="hp-carousel-doctor-profile" data-slide-id="2">
      <img src="https://picsum.photos/300/300" class="d-block" alt="...">
      <a href="">
        <h3>DOCTORA 2</h3>
        <h3>NOMBRE</h3>
        <h3>APELLIDO</h3>
        <p>ESPECIALIDAD</p>
      </a>
    </div>
    <div class="hp-carousel-doctor-profile" data-slide-id="3">
      <img src="https://picsum.photos/300/300" class="d-block" alt="...">
      <a href="">
        <h3>DOCTORA 3</h3>
        <h3>NOMBRE</h3>
        <h3>APELLIDO</h3>
        <p>ESPECIALIDAD</p>
      </a>
    </div>
  </div>
</div>

<%= render 'shared/doctor_contact_form' %>

app/views/shared/_doctor_contact_form.html.erb
<!-- Modal -->
<div class="modal fade" id="contactFormDoctor" tabindex="-1" role="dialog" aria-labelledby="contactFormDoctorLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="contactFormDoctorLabel">Contacto</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_tag doctor_contact_form_path do %>
          <div class="form-group">
            <div class="row">
              <div class="col">
                <%= text_field_tag :name, nil, placeholder: 'Nombre', class: "form-control"  %>
              </div>
              <div class="col">
                <%= text_field_tag :surname, nil, placeholder: 'Apellido', class: "form-control"  %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col">
                <%= email_field_tag :email, nil, placeholder: 'Email', class: "form-control"  %>
              </div>
              <div class="col">
                <%= phone_field_tag :phone, nil, placeholder: 'Teléfono', class: "form-control"  %>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="row">
              <div class="col">
                <%= text_area_tag :message, nil, placeholder: 'Mensaje', class: "form-control"  %>
              </div>
            </div>
          </div>
          <%= submit_tag 'Envíar', class: 'btn btn-blue small w-100' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<!-- to deal with AJAX flash messages we created a custom js flash element -->
<!-- it is not displayed by default and need to be manually triggered if needed -->
<div class="js-flash display-none">
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <span class='js-flash-message'></span>
    <button class='close close-js-flash'>
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <%= link_to '#top-banner' do %>
      <%= inline_svg_tag('logo-footer.svg', class: 'logo-footer') %>
    <% end %>
    <div class="footer-items">
      <div class="footer-item">
        <h5><%= link_to 'NOSOTROS', about_us_path %></h5>
        <p><%= link_to 'TÉRMINOS Y CONDICIONES', terms_and_conditions_path %></p>
        <p><%= link_to 'POLÍTICA DE PRIVACIDAD', privacy_policy_path %></p>
        <p><%= link_to 'VENTAS AL POR MAYOR', wholesales_path %></p>
        <p><%= link_to 'COVID 19', covid_19_path %></p>
      </div>
      <div class="footer-item">
        <h5>CONTÁCTANOS</h5>
        <p><a href="https://wa.me/+50766718821" target="_blank"><i class="fab fa-whatsapp"></i> POR WHATSAPP</a></p>
        <p><%= link_to 'PREGUNTAS FRECUENTES', faq_path %></p>
        <p><%= link_to 'CAMBIOS Y DEVOLUCIONES', returns_and_exchanges_path %></p>
      </div>
      <div class="footer-item">
        <h5>HORARIOS DE ENTREGA</h5>
        <p>LUNES A VIERNES 9:00 AM / 6.00 PM</p>
        <p>SABADOS 9:00 AM / 5:00 PM</p>
        <p><%= link_to 'ENVÍOS Y ÁREAS DE COBERTURA', shipping_path %></p>
      </div>
    </div>
    <div class="social">
      <div class="hide-under-768"></div>
      <div class="">
        <%= link_to "https://www.instagram.com/blueforest.panama/", target: "_blank" do %>
          <%= image_tag 'instagram.png' %>
        <% end %>
        <%#= image_tag 'facebook.png' %>
        <%#= image_tag 'twitter.png' %>
      </div>
      <div class="hide-under-768"></div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="container navbar-container">
  <div class="nav-item search mobile">
    <%= form_tag search_products_path, method: :get, class: 'form-inline' do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "BUSCAR PRODUCTOS"
      %>
      <%= button_tag type: "submit", class: "btn" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>
  <div class="navbar navbar-expand-sm navbar-light navbar-blueforest">
    <%= link_to root_path, class: "navbar-brand grow-1" do %>
        <% inline_svg_tag("logo.svg") %>
      <% end %>

    <button class="navbar-toggler">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="navbar-collapse">
      <button class="navbar-toggler">
        <%= image_tag 'flechas-02.png' %>
      </button>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item search desktop">
          <%= form_tag search_products_path, method: :get, class: 'form-inline' do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "BUSCAR PRODUCTOS"
            %>
            <%= button_tag type: "submit", class: "btn" do %>
              <i class="fas fa-search"></i>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">PRODUCTOS</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% @categories.each do |category| %>
              <%= link_to category.name.capitalize, category_path(category), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">MI CUENTA</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Mis datos", dashboards_path(anchor: 'profile'), class: "dropdown-item" %>
              <%= link_to "Mis ordenes", dashboards_path(anchor: 'orders'), class: "dropdown-item" %>
              <%= link_to "Mis Favoritos", dashboards_path(anchor: 'favorites'), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">MI CUENTA</a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Crea tu cuenta", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Ingresa", new_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="cart-list">
      <div class="nav-item cart-icon cart-toggle open-sidebar-cart simple-flexbox">
        <%= inline_svg_tag('cart.svg') %>
        <% if @current_cart.total_items > 0 %>
          <span><%= @current_cart.total_items %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_order_breadcrumb.html.erb
  <div id="order-breadcrumb" class="w-100">
    <div class="order-breadcrumb-item <%= @breadcrumb_contact_class %>">
      <div class="number">1</div>
      <span>INFORMACIÓN DE CONTACTO</span>
    </div>
    <div class="order-breadcrumb-item <%= @breadcrumb_shipping_class %>">
      <div class="number">2</div>
      <span>DIRECCIÓN</span>
    </div>
    <div class="order-breadcrumb-item <%= @breadcrumb_review_class %>">
      <div class="number">3</div>
      <span>REVISIÓN</span>
    </div>
    <div class="order-breadcrumb-item <%= @breadcrumb_confirm_class %>">
      <div class="number">4</div>
      <span>CONFIRMACIÓN</span>
    </div>
  </div>

app/views/shared/_products_grid.html.erb
<div class="products" id='products'>
  <% @products.each do |product| %>
    <% if product.product_variations.length > 0 %>
      <div class="product">
        <!-- iterate over product photos, find the main photos -->
        <!-- take the first on of the main photos and break the iteration -->
        <% if !product.product_photos.empty? %>
          <% product.product_photos.each do |product_photo| %>
            <% if product_photo.main %>
              <%= cl_image_tag product_photo.photos[0].key, height: 400, crop: :fill %>
              <% break %>
            <% end %>
          <% end %>
        <% else %>
          <div class="product-photo-placeholder"></div>
        <% end %>
        <div class="product-grid-info-container">
          <div class="grid-symbol simple-flexbox"><%= inline_svg_tag('symbol.svg') %></div>
          <div class="cta-grid" data-controller="favorite">
            <!-- if there is only 1 product variation, show the option to add to cart from the home page directly -->
            <% if product.product_variations.length == 1 %>
              <% if product.product_variations.first.quantity > 0 %>
                <%= link_to line_items_path(variation_id: product.product_variations.first, quantity: 1, atc_from_grid: true, full_path: request.fullpath), method: 'post' do %>
                  <%= inline_svg_tag('cart.svg') %>
                <% end %>
              <% else %>
                <span>AGOTADO</span>
              <% end %>
            <% end %>
            <!-- if user is signed in, we need to check if the product is within its favorites -->
            <!-- if yes we show a 'full' like symbol, and the link will be to remove the product from its favorites -->
            <!-- if no, we show a 'stroked' like symbol, and the link will be to add the product to its favorites -->
            <div class="flex-grow-1">
              <% if user_signed_in? && (matching_product_favorite = @product_favorites.find { |product_favorite| product_favorite.product_id == product.id }) %>
                <span data-action='click->favorite#removeFavorite' data-target="favorite.toggle" data-favorite-id='<%= matching_product_favorite.id %>' data-product-id='<%= product.id %>'>
                  <%= inline_svg_tag('like.svg', class: 'liked', data: { target: 'favorite.icon' }) %>
                </span>
              <% else %>
                <span data-action='click->favorite#addFavorite' data-target="favorite.toggle" data-product-id='<%= product.id %>' >
                  <%= inline_svg_tag('like.svg', data: { target: 'favorite.icon' }) %>
                </span>
              <% end %>
            </div>
          </div>
          <div class="product-grid-info">
            <p class="product-title"><b><%= product.name.upcase %></b></p>
            <% price = nil %>
            <% discount_price = nil %>
            <% product.product_variations.each_with_index do |product_variation, i| %>
              <% if product_variation.color == product.main_color %>
                <% if !price %>
                  <% price = product_variation.price %>
                  <% discount_price = product_variation.discount_price if product_variation.discount_price %>
                <% elsif product_variation.price < price %>
                  <% price = product_variation.price %>
                  <% discount_price = product_variation.discount_price if product_variation.discount_price %>
                <% end %>
              <% end %>
            <% end %>
            <p class="product-price">
              <% if discount_price %>
                <span class="crossed-white"><%= number_to_currency(price, precision: 2) %></span> <%= number_to_currency(discount_price, precision: 2) %>
              <% elsif price %>
                <%= number_to_currency(price, precision: 2) %>
              <% else %>
                <!-- Just a security if for some reason price is still empty... -->
                <%= number_to_currency(product.product_variations.first.price, precision: 2) %>
              <% end %>
            </p>
            <%= link_to product_path(product), class: 'simple-flexbox product-hover' do %>
              <div>
                <h3><%= product.name.upcase %></h3>
                <p><%= product.short_description.upcase.truncate(50) if product.short_description %></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_sidebar_cart.html.erb
<div id="sidebar-cart">
  <div class="sidebar-cart-header">
    <span class="cart-toggle close-sidebar-cart"><%= image_tag 'flechas-02.png' %></span>
    <b>MI CARRITO</b>
  </div>
  <% if @current_cart.line_items.count > 0 %>
    <div class="padding-30 sidebar-cart-content">
      <div class="d-flex flex-column">
        <% total_quantity = 0 %>
        <% @current_cart.line_items.each do |line_item| %>
          <div class="cart-product d-flex align-items-center" data-line-item=<%= line_item.id %>>
            <% if line_item.photo_key %>
              <%= cl_image_tag line_item.photo_key, height: 150, width: 150, crop: :fill %>
            <% else %>
              <div class="product-photo-placeholder-small"></div>
            <% end %>
            <div class="grow-1 cart-product-info">
              <p>
                <b>
                  <%= link_to line_item.product_variation.product.name, product_path(line_item.product_variation.product.id) %>
                </b>
              </p>
              <% if line_item.product_variation.color %>
                <p>Color: <%= t(line_item.product_variation.color) %></p>
              <% end %>
              <p>Tamaño: <%= line_item.product_variation.size %></p>
              <p>
                <% if line_item.product_variation.discount_price %>
                  <span class="crossed"><%= number_to_currency(line_item.product_variation.price, precision: 2) %></span>
                  <span><%= number_to_currency(line_item.product_variation.discount_price, precision: 2) %></span>
                <% else %>
                  <%= number_to_currency(line_item.product_variation.price, precision: 2) %>
                <% end %>
              </p>
            </div>
            <!-- the quantity counter is wrapped around stimulus js 'counter' controller -->
            <!-- it allows to trigger the 'quantityTrigger' js action when a button is clicked -->
            <div class="quantity-counter d-flex" data-controller="counter">
              <button data-action='click->counter#quantityTrigger' <%= 'disabled' if line_item.quantity == 1 %>>-</button>
              <span class="grow-1 text-center" data-target="counter.count" data-line-item=<%= line_item.id %>><%= line_item.quantity %></span>
              <button data-action='click->counter#quantityTrigger'>+</button>
            </div>
          </div>
          <% total_quantity += line_item.quantity %>
        <% end %>
      </div>
    </div>
    <div class="sidebar-cart-footer">
      <div class="text-right sidebar-cart-footer-top">
        <p class="total_items">
          <%= total_quantity %> <%= t('products', count: total_quantity) %>
        </p>
        <p><b>Sub Total: <span class="sub_total"><%= number_to_currency(@current_cart.sub_total, precision: 2) %></span></b></p>
      </div>
      <div class="w-100 text-center">
        <% if user_signed_in? %>
          <%= link_to "ORDENAR", new_user_order_path(current_user), class: 'btn btn-blue w-100' %>
        <% elsif params[:fake_user_id] %>
          <p><%= link_to "Finalizar Orden", new_fake_user_order_path(params[:fake_user_id]), class: 'btn btn-blue w-100' %></p>
        <% else %>
          <%= link_to "ORDENAR", new_fake_user_path, class: 'btn btn-blue w-100' %>
        <% end %>
        <%= link_to "Ver carrito", cart_path(session[:cart_id]) %>
      </div>
      <div class="sidebar-cart-footer-bottom">
        <p class='text-center mb-0'>Todos los pagos se hacen contra entrega.</p>
        <div class="payment-logos">
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088125/payments-logo/1-visa_unvmtw.png', width: 35, crop: :fill %>
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/2-mastercard_scrnh5.png', width: 35, crop: :fill %>
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088123/payments-logo/3-clave_dzrpsj.png', width: 35, crop: :fill %>
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/4-yappy_mzep5g.png', width: 35, crop: :fill %>
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/5-ach_omk444.png', width: 35, crop: :fill %>
          <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/6-cash_tl42zl.png', width: 35, crop: :fill %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="padding-30">
      <p>Carrito vacillo.</p>
      <%= link_to 'Ver productos', root_path(anchor: 'products') %></p>
    </div>
  <% end %>
</div>

app/views/shared/_top_banner.html.erb
<div class="top-banner simple-flexbox" id="top-banner">
  <h6>Envíos gratuitos en ordenes sobre $65.00</h6>
</div>