config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [] do
    resources :orders, only: %i[index show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :carts, only: :show
  resources :products do
    collection do
      get :search
    end
  end

  resources :product_variations

  resources :line_items, only: %i[create destroy] do
    member do
      post :change_quantity
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :fake_users, only: %i[new create edit update] do
    resources :orders, only: %i[show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :categories, only: :show

  resources :product_favorites, only: %i[create destroy]

  # custom route to redirect user to the correct page
  # when they start an order and want to login after
  get 'login_before_new_order', to: 'orders#login_before_new'

  # route to the user profile page
  get 'dashboards', to: 'dashboards#dashboard'

  # route for product creation tool
  get 'product_creation', to: 'dashboards#product_creation_new'
  post 'product_creation', to: 'dashboards#product_creation_create'
  root to: 'products#index'

  # routes for info pages
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get 'returns_and_exchanges', to: 'pages#returns_and_exchanges'
  get 'shipping', to: 'pages#shipping'
  get 'faq', to: 'pages#faq'
  get 'about_us', to: 'pages#about_us'
  get 'covid_19', to: 'pages#covid_19'
  get 'wholesales', to: 'pages#wholesales'

  # route form doctor contact form
  post 'doctor_contact_form', to: 'doctors#doctor_contact_form'
end

app/models/order.rb
class Order < ApplicationRecord
  STATUS = %w[confirmed pick_pack shipping delivered].freeze
  belongs_to :user, optional: true
  belongs_to :fake_user, optional: true
  has_many :line_items, dependent: :destroy
  has_many :product_variations, through: :line_items

  validates :sub_total, :total_items, :shipping, :itbms, :total, presence: true
  validates :status, inclusion: { in: STATUS, message:
    ': Please choose between confirmed, pick_pack, shipping, delivered' }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, except: :login_before_new
  before_action :new_order, only: %i[new create]
  before_action :find_user, except: :login_before_new

  def show
    # prevent users from trying to access other users orders by changing the order id in the url
    redirect_to root_path and return if session[:order_id] != params[:id].to_i

    @order = Order.find(params[:id])

    # for now we will considere that users only have 1 address, so always take the first one
    # we could easily have users with many addresses in the future
    @address = @user.addresses.first
    set_breadcrumb_classes('hide-under-576', 'hide-under-576', nil, 'active')
  end

  def new
    # for now we will considere that users only have 1 address, so always take the first one
    # we could easily have users with many addresses in the future
    @address = @user.addresses.first
    set_breadcrumb_classes('hide-under-576', 'hide-under-576', 'active', 'pending')
  end

  def create
    user_signed_in? ? @order.user = @user : @order.fake_user = @user

    attach_cart_line_items_to_order
    attach_cart_details_to_order
    @order.save

    # link order to the session
    session[:order_id] = @order.id

    # destroy the current cart, because order has been confirmed
    # user can now create new cart with new products
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil

    send_confirmations_emails
    redirect_to_correct_path
  end

  # aditional method and route just to redirect users to the correct new order path
  # if they start creating an order without being logged in and wants to log in after
  def login_before_new
    redirect_to new_user_order_path(current_user)
  end

  private

  def find_user
    if user_signed_in?
      @user = current_user

      # security check that current user has an address
      redirect_to new_user_address_path(@user) if @user.addresses.empty?
    else
      @user = FakeUser.includes(:addresses).find(params[:fake_user_id])
    end
  end

  def new_order
    @order = Order.new
  end

  # define what part of order breadcrumb is active/pending or hidden en mobile
  # (depending on what step we are on the order funnel)
  # those are css classes
  def set_breadcrumb_classes(contact_class, shipping_class, review_class, confirm_class)
    @breadcrumb_contact_class = contact_class
    @breadcrumb_shipping_class = shipping_class
    @breadcrumb_review_class = review_class
    @breadcrumb_confirm_class = confirm_class
  end

  # append all line items of current cart to the order
  def attach_cart_line_items_to_order
    @current_cart.line_items.each do |line_item|
      @order.line_items << line_item

      # reduce stock quantity product variation by the quantity purchased of each line item
      new_quantity = line_item.product_variation.quantity - line_item.quantity
      line_item.product_variation.update(quantity: new_quantity)

      # remove the link between theses line items and the current cart
      # otherwises they will be destroyed when we destroy the cart later
      # (because of dependent destroy between cart and line items)
      line_item.cart_id = nil
    end
  end

  # append all order details of current cart to the order
  def attach_cart_details_to_order
    @order.sub_total = @current_cart.sub_total
    @order.total_items = @current_cart.total_items
    @order.shipping = @current_cart.shipping
    @order.itbms = @current_cart.itbms
    @order.total = @current_cart.total
  end

  def send_confirmations_emails
    # send confirmation email
    OrderMailer.confirmation(@order).deliver_now
    # send new order notice email (to admin)
    OrderMailer.new_order_notice(@order).deliver_now
  end

  # redirect to correct path regarding if its a user or a fake user
  def redirect_to_correct_path
    if user_signed_in?
      redirect_to user_order_path(@user, @order)
    else
      redirect_to fake_user_order_path(@user, @order)
    end
  end
end

app/views/orders/new.html.erb
<div class="container orders-funnel">
  <%= render 'shared/order_breadcrumb' %>
  <br>
  <h1>REVISIÓN DEL PEDIDO</h1>

  <div class="order-review">
    <div class="order-summary">
      <% fake_user_params = user_signed_in? ? nil : @user.id  %>
      <%= link_to cart_path(@current_cart, fake_user_id: fake_user_params) do %>
        <i class="fas fa-pen"></i>
      <% end %>
      <% total_quantity = 0 %>
      <% @current_cart.line_items.reverse.each do |line_item| %>
        <div class="cart-product d-flex align-items-center">
          <% if line_item.photo_key %>
            <%= cl_image_tag line_item.photo_key, height: 150, width: 150, crop: :fill %>
          <% else %>
            <div class="product-photo-placeholder-small"></div>
          <% end %>
          <div class="grow-1">
            <p><b><%= line_item.product_variation.product.name %></b></p>
            <% if line_item.product_variation.color %>
              <p>Color: <%= t(line_item.product_variation.color) %></p>
            <% end %>
            <p>Tamaño: <%= line_item.product_variation.size %></p>
            <p>
              <% if line_item.product_variation.discount_price %>
                <span class="crossed"><%= number_to_currency(line_item.product_variation.price, precision: 2) %></span>
                <span><%= number_to_currency(line_item.product_variation.discount_price, precision: 2) %></span>
              <% else %>
                <%= number_to_currency(line_item.product_variation.price, precision: 2) %>
              <% end %>
            </p>
            <p>Cantidad: <%= line_item.quantity %></p>
          </div>
          <% total_quantity += line_item.quantity %>
        </div>
      <% end %>
    </div>
    <div class="order-detail">
      <div class="position-relative">
        <% if user_signed_in? %>
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% else %>
          <%= link_to edit_fake_user_path(@user) do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% end %>
        <h2>Información de contacto</h2>
        <p><%= @user.first_name %> <%= @user.last_name %></p>
        <p><%= @user.email %></p>
        <p><%= @user.phone %></p>
      </div>
      <div class="position-relative">
        <h2>Dirección</h2>
        <% if user_signed_in? %>
          <%= link_to edit_user_address_path(@user, @address) do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% else %>
          <%= link_to edit_fake_user_address_path(@user, @address) do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% end %>
        <p><%= @address.street %></p>
        <p><%= @address.flat_number %></p>
        <p><%= @address.district %></p>
        <p><%= @address.area %></p>
        <p><%= @address.detail %></p>
        <p><%= @address.city %></p>
        <div id="show-address-map"
         style="width: 100%; height: 200px;"
         data-lat="<%= @address.latitude %>"
         data-lng="<%= @address.longitude %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
  <div class="order-review-footer">
    <div class="my-3">
      <p><%= total_quantity %> <%= t('products', count: total_quantity) %></p>
      <p>Sub Total: <%= number_to_currency(@current_cart.sub_total, precision: 2) %></p>
       <p>Entrega:
          <% if @current_cart.shipping > 0 %>
            <%= number_to_currency(@current_cart.shipping, precision: 2) %>
          <% else %>
            <b>¡Envío gratuito!</b>
          <% end %>
        </p>
      <p>ITBMS (7%): <%= number_to_currency(@current_cart.itbms, precision: 2) %></p>
      <p><b>TOTAL: <%= number_to_currency(@current_cart.total, precision: 2) %></b></p>
    </div>
    <% if user_signed_in? %>
      <%= link_to "CONFIRMAR PEDIDO", user_orders_path, method: :post, class: 'btn btn-yellow w-100' %>
    <% else %>
      <%= link_to "CONFIRMAR PEDIDO", fake_user_orders_path, method: :post, class: 'btn btn-yellow w-100' %>
    <% end %>
    <div class="order-review-footer-bottom mt-3">
      <p class='text-center'>Todos los pagos se hacen contra entrega. Gracias por preferirnos.</p>
      <div class="payment-logos">
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088125/payments-logo/1-visa_unvmtw.png', width: 50, crop: :fill, style: 'background-color: white, padding: 10px;' %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/2-mastercard_scrnh5.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088123/payments-logo/3-clave_dzrpsj.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/4-yappy_mzep5g.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/5-ach_omk444.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/6-cash2_vkbbym.png', width: 50, crop: :fill %>
      </div>
    </div>
  </div>
</div>

app/views/orders/shipping.html.erb
<div class="container mt-5">

  <div id="order-breadcrumb" class="d-flex w-100 mb-5">
    <div class="d-flex flex-column align-items-center">
      <div class="number">1</div>
      <span>Carrito</span>
    </div>
    <div class="d-flex flex-column align-items-center active">
      <div class="number">2</div>
      <span>Dirección</span>
    </div>
    <div class="d-flex flex-column align-items-center">
      <div class="number">3</div>
      <span>Confirmación</span>
    </div>
  </div>

  <h1>Sus datos de contacto para la entrega</h1>
  <% if user_signed_in? %>
      <p><%= current_user.first_name %></p>
      <p><%= current_user.last_name %></p>
      <p><%= current_user.email %></p>
      <p><%= current_user.address %></p>
      <p><%= link_to "Confirm", orders_path, method: :post, class: "btn btn-secondary w-100" %></p>
  <% else %>
      <p>
        Ya tienes una cuenta? Porfavor <%= link_to 'Conectarse', new_user_session_path %> o <%= link_to 'Crear cuenta', new_user_registration_path %>
      </p>
      <p>O contuniar sin creación de cuenta:</p>
      <%= form_tag orders_path, method: :post, class: ""  do %>
        <div class="form-row">
          <div class="form-group col">
            <%= text_field_tag 'fake_user[first_name]', nil, placeholder: 'Primer nombre', class: "form-control" %>
          </div>
          <div class="form-group col">
            <%= text_field_tag 'fake_user[last_name]', nil, placeholder: 'Apellido', class: "form-control" %>
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col">
            <%= text_field_tag 'fake_user[email]', nil, placeholder: 'Correo', class: "form-control" %>
          </div>
          <div class="form-group col">
            <%= text_field_tag 'fake_user[phone]', nil, placeholder: 'Teléfono', class: "form-control" %>
          </div>
        </div>
      <%= submit_tag %>
        <b>Dirección</b>

          <%= simple_form_for(@address) do |f| %>
            <%= f.input :street %>
            <%= f.input :flat_number %>
            <%= f.input :district %>
            <%= f.input :detail %>
            <%= f.input :city %>
            <%= f.submit %>
          <% end %>

        <button class="btn btn-secondary">Elegir en el mapa</button>
        <%= Geocoder.search("PH Zaphiro, Panama") %>
        <div id="map"
         style="width: 100%; height: 600px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

        <%= button_tag type: "submit", class: "btn btn-secondary w-100" do %>
          Confirm
        <% end %>
      <% end %>
  <% end %>
  <hr>
</div>

app/views/orders/show.html.erb
<div class="container orders-funnel">
  <%= render 'shared/order_breadcrumb' %>
  <br>
  <h1>¡PEDIDO CONFIRMADO!</h1>

  <div class="order-review">
    <div class="order-summary">
      <% total_quantity = 0 %>
      <% @order.line_items.reverse.each do |line_item| %>
        <div class="cart-product d-flex align-items-center">
          <% if line_item.photo_key %>
            <%= cl_image_tag line_item.photo_key, height: 150, width: 150, crop: :fill %>
          <% else %>
            <div class="product-photo-placeholder-small"></div>
          <% end %>
          <div class="grow-1">
            <p><b><%= line_item.product_variation.product.name %></b></p>
            <% if line_item.product_variation.color %>
              <p>Color: <%= t(line_item.product_variation.color) %></p>
            <% end %>
            <p>Tamaño: <%= line_item.product_variation.size %></p>
            <p>
              <% if line_item.product_variation.discount_price %>
                <span class="crossed"><%= number_to_currency(line_item.product_variation.price, precision: 2) %></span>
                <span><%= number_to_currency(line_item.product_variation.discount_price, precision: 2) %></span>
              <% else %>
                <%= number_to_currency(line_item.product_variation.price, precision: 2) %>
              <% end %>
            </p>
            <p>Cantidad: <%= line_item.quantity %></p>
          </div>
          <% total_quantity += line_item.quantity %>
        </div>
      <% end %>
    </div>
    <div class="order-detail">
      <h2>Información de contacto</h2>
      <p><%= @user.first_name %> <%= @user.last_name %></p>
      <p><%= @user.email %></p>
      <p><%= @user.phone %></p>
      <h2>Dirección</h2>
      <p><%= @address.street %></p>
      <p><%= @address.flat_number %></p>
      <p><%= @address.district %></p>
      <p><%= @address.area %></p>
      <p><%= @address.detail %></p>
      <p><%= @address.city %></p>
      <div id="show-address-map"
       style="width: 100%; height: 200px;"
       data-lat="<%= @address.latitude %>"
       data-lng="<%= @address.longitude %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
  <div class="order-review-footer">
    <div class="my-3">
      <p><%= total_quantity %> <%= t('products', count: total_quantity) %></p>
      <p>Sub Total: <%= number_to_currency(@order.sub_total, precision: 2) %></p>
       <p>Entrega:
          <% if @order.shipping > 0 %>
            <%= number_to_currency(@order.shipping, precision: 2) %>
          <% else %>
            <b>¡Envío gratuito!</b>
          <% end %>
        </p>
      <p>ITBMS (7%): <%= number_to_currency(@order.itbms, precision: 2) %></p>
      <p><b>TOTAL: <%= number_to_currency(@order.total, precision: 2) %></b></p>
    </div>
    <div class="order-review-footer-bottom mt-3">
      <p class='text-center'>Todos los pagos se hacen contra entrega. Gracias por preferirnos.</p>
      <div class="payment-logos">
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088125/payments-logo/1-visa_unvmtw.png', width: 50, crop: :fill, style: 'background-color: white, padding: 10px;' %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/2-mastercard_scrnh5.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088123/payments-logo/3-clave_dzrpsj.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/4-yappy_mzep5g.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/5-ach_omk444.png', width: 50, crop: :fill %>
        <%= cl_image_tag 'https://res.cloudinary.com/blueforest/image/upload/v1591088122/payments-logo/6-cash2_vkbbym.png', width: 50, crop: :fill %>
      </div>
    </div>
  </div>
</div>