config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [] do
    resources :orders, only: %i[index show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :carts, only: :show
  resources :products do
    collection do
      get :search
    end
  end

  resources :product_variations

  resources :line_items, only: %i[create destroy] do
    member do
      post :change_quantity
      post :add_quantity
      post :reduce_quantity
    end
  end

  resources :fake_users, only: %i[new create edit update] do
    resources :orders, only: %i[show new create]
    resources :addresses, only: %i[new create edit update]
  end

  resources :categories, only: :show

  resources :product_favorites, only: %i[create destroy]

  # custom route to redirect user to the correct page
  # when they start an order and want to login after
  get 'login_before_new_order', to: 'orders#login_before_new'

  # route to the user profile page
  get 'dashboards', to: 'dashboards#dashboard'

  # route for product creation tool
  get 'product_creation', to: 'dashboards#product_creation_new'
  post 'product_creation', to: 'dashboards#product_creation_create'
  root to: 'products#index'

  # routes for info pages
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get 'returns_and_exchanges', to: 'pages#returns_and_exchanges'
  get 'shipping', to: 'pages#shipping'
  get 'faq', to: 'pages#faq'
  get 'about_us', to: 'pages#about_us'
  get 'covid_19', to: 'pages#covid_19'
  get 'wholesales', to: 'pages#wholesales'

  # route form doctor contact form
  post 'doctor_contact_form', to: 'doctors#doctor_contact_form'
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def dashboard
    @address = current_user.addresses.first
    @orders = current_user.orders
                          .includes(line_items: [product_variation: :product])
                          .order(created_at: :desc)
    @favorites = current_user.product_favorites
                             .includes(product: [product_photos: [photos_attachments: :blob]])
                             .order(created_at: :desc)
  end

  def product_creation_new
    unless current_user.admin
      flash[:alert] = 'Need admin rights to create products'
      redirect_to root_path
      return
    end

    @product = Product.new
    @product_variation = ProductVariation.new
    @photo = ProductPhoto.new

    @colors = ProductVariation::COLORS.map { |key, _| "<option value='#{key}'>#{key}</option>" }
  end

  def product_creation_create
    create_product
    create_product_variations
    flash[:notice] = 'Product Created'
    redirect_to product_creation_path
  end

  private

  # def form_validation
  #   result = { valid?: true, error_message: '' }

  #   if params[:name].empty?
  #     result[:valid?] = false
  #     result[:error_message] = 'Product name is empty'
  #   elsif params[:product_type] == 'without_colors'
  #     params[:color_variations].each do |color_variation|
  #       next if color_variation[:color] != 'unique'

  #       color_variation[:size_variations].each do |size_variation|
  #         if size_variation[:size].empty?
  #           result[:valid?] = false
  #           result[:error_message] = 'Size is empty'
  #         elsif size_variation[:price].empty?
  #           result[:valid?] = false
  #           result[:error_message] = 'Price is empty'
  #         elsif size_variation[:quantity].empty?
  #           result[:valid?] = false
  #           result[:error_message] = 'Price is empty'
  #         end
  #       end
  #     end
  #   end
  #   result
  # end

  def create_product
    # create a new product with product creation form params
    @product = Product.new(
      name: params[:name],
      short_description: params[:short_description],
      long_description: params[:long_description]
    )
    @product.published = params[:published] ? true : false
    @product.save!
  end

  def create_product_variations
    # iterate over all color variations params
    params[:color_variations].each do |color_variation|
      # both product 'without colors' and 'with colors' options are present on the form DOM
      # So even for a product without color, the form will have (empty) color variations params
      # (and the contrary as well)
      # but for product variation without color, color value is 'unique' by default'
      # So for product 'without colors', we can skip product variations without the color 'unique'
      # And for product 'with colors', we can skip product variations with the color 'unique'
      next if params[:product_type] == 'without_colors' && color_variation[:color] != 'unique'
      next if params[:product_type] == 'with_colors' && color_variation[:color] == 'unique'

      # iterate over size variations params
      create_size_variations(color_variation)
      create_product_photos(color_variation)
    end
  end

  def create_size_variations(color_variation)
    color_variation[:size_variations].each do |size_variation|
      # for each size variation, create a new Product Variation with size variation params
      product_variation = ProductVariation.new(
        product_id: @product.id, size: size_variation[:size].strip,
        price: size_variation[:price].strip,
        discount_price: size_variation[:discount_price].strip,
        quantity: size_variation[:quantity].strip
      )

      # product variation color need to stay empty if there is no colors
      # so put the color variation params unless the color value is 'unique'
      product_variation.color = color_variation[:color] unless color_variation[:color] == 'unique'
      product_variation.save!
    end
  end

  def create_product_photos(color_variation)
    # create a new instance of product photos and attach it to the product
    @product_photo = ProductPhoto.new
    @product_photo.product = @product

    create_photos_array(color_variation)
    return if @photos.empty?

    # attach all photos to this product photo instance
    @product_photo.photos.attach(@photos)
    # product photo color need to stay empty if there is no colors
    # so put the color name unless the color value is 'unique'
    @product_photo.color = color_variation[:color] unless color_variation[:color] == 'unique'
    @product_photo.save!
  end

  def create_photos_array(color_variation)
    # initialize a photo array
    @photos = []

    # iterate over photos params
    color_variation[:photos].each do |variation_photo|
      next unless variation_photo[:photo]

      if variation_photo[:main]
        # if this is the main photo, put the photo at the beginning of the photos array
        # and set this product photo as the main one
        # (so that, the main photo will always be the first one of the product photos array)
        @photos.unshift(photo_hash(variation_photo))
        @product_photo.main = true
      else
        # otherwise just add photo to the photos array
        @photos << photo_hash(variation_photo)
      end
    end
  end

  def photo_hash(variation_photo)
    { io: variation_photo[:photo],
      filename: @product.name,
      content_type: variation_photo[:photo].content_type }
  end
end

app/views/dashboards/dashboard.html.erb
<div class="dashboard-container container">
  <h1>MI CUENTA</h1>
  <ul class="nav nav-tabs" id="dashboardTab" role="tablist">
    <li class="nav-item" role="presentation">
      <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="true">Mi Perfil</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="orders-tab" data-toggle="tab" href="#orders" role="tab" aria-controls="orders" aria-selected="false">Mis Ordenes</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link" id="favorites-tab" data-toggle="tab" href="#favorites" role="tab" aria-controls="favorites" aria-selected="false">Favoritos</a>
    </li>
  </ul>

  <div class="tab-content" id="dashboard">
    <div class="tab-pane fade show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
      <div class="dashboard-profile">
        <div class="dashboard-info">
          <div class="position-relative">
              <%= link_to edit_user_registration_path(from_dashboard: true) do %>
                <i class="fas fa-pen"></i>
              <% end %>
            <h2>Información de contacto</h2>
            <p><%= current_user.first_name %> <%= current_user.last_name %></p>
            <p><%= current_user.email %></p>
            <p><%= current_user.phone %></p>
          </div>
          <div class="position-relative">
            <h2>Dirección</h2>
            <% if @address %>
              <%= link_to edit_user_address_path(current_user, @address, from_dashboard: true) do %>
                <i class="fas fa-pen"></i>
              <% end %>
              <p><%= @address.street %></p>
              <p><%= @address.flat_number %></p>
              <p><%= @address.district %></p>
              <p><%= @address.area %></p>
              <p><%= @address.detail %></p>
              <p><%= @address.city %></p>
            <% else %>
              <p>No tienes dirección registrada</p>
              <%= link_to 'Registrar dirección', new_user_address_path(current_user, from_dashboard: true), class: 'btn btn-blue' %>
            <% end %>
          </div>
        </div>
        <% if @address %>
          <div id="show-address-map" class="dashboard-map"
           style="width: 100%"
           data-lat="<%= @address.latitude %>"
           data-lng="<%= @address.longitude %>"
           data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        <% end %>
      </div>
    </div>
    <div class="tab-pane fade" id="orders" role="tabpanel" aria-labelledby="orders-tab">
      <% if !@orders.empty? %>
        <% @orders.each do |order| %>
          <div class="dashboard-order">
            <div>
              <p><b>Fecha</b></p>
              <span><%= order.created_at.strftime("%-d %B %Y") %></span>
            </div>
            <div>
              <p><b><%= pluralize(order.total_items.to_i, 'producto') %></b></p>
              <div>
                <% order.line_items.each do |item| %>
                  <%= link_to product_path(item.product_variation.product) do %>
                    <p class="mb-0"><%= item.product_variation.name %> <%= "(x #{item.quantity})" if item.quantity > 1%></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div>
              <p><b>Entrega</b></p>
              <span>$<%= order.shipping %></span>
            </div>
            <div>
              <p><b>Total</b></p>
              <span>$<%= order.total %></span>
            </div>
          </div>
        <% end %>
      <% else %>
          <p>No tienes ningún orden</p>
          <%= link_to 'Descrubrir Productos', root_path(anchor: 'products'), class: 'btn btn-blue' %>
      <% end %>
    </div>
    <div class="tab-pane fade" id="favorites" role="tabpanel" aria-labelledby="favorites-tab">
      <div class="dashboard-favorites" data-controller="favorite" >
        <% if @favorites.count > 0 %>
          <% @favorites.each do |favorite| %>
            <div class="d-flex align-items-center dashboard-favorites-products" data-target="favorite.product">
              <% if !favorite.product.product_photos.empty? %>
                <%= cl_image_tag favorite.product.product_photos.first.photos.first.key, height: 150, width: 150, crop: :fill %>
              <% else %>
                <div class="product-photo-placeholder-small"></div>
              <% end %>
              <div class="grow-1">
                <p><b><%= favorite.product.name %></b></p>
                <p><%= favorite.product.short_description %></p>
              </div>
              <%= link_to '', product_path(favorite.product), class: 'link-overlay' %>
              <div class='remove-favorite'>
                <span data-action='click->favorite#removeFavoriteFromDashboard' data-target="favorite.toggle" data-favorite-id='<%= favorite.id %>'>
                  <%= inline_svg_tag('like.svg') %>
                </span>
              </div>
            </div>
          <% end %>
        <% else %>
          <p>No tienes ningún producto favorito</p>
          <%= link_to 'Descrubrir Productos', root_path(anchor: 'products'), class: 'btn btn-blue' %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/dashboards/product_creation_new.html.erb
<div class="container my-5" id='product-creation-container'>
  <h1>Create New Product</h1>
  <br>
  <%= form_tag product_creation_path, multipart: true, id: 'product-creation-form' do %>
    <div class="form-group">
      <%= label_tag  :name, "Name" %>
      <%= text_field_tag :name, nil, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= label_tag  :short_description, "Short Description" %>
      <%= text_field_tag :short_description, nil, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= label_tag  :long_description, "Long Description" %>
      <%= text_area_tag :long_description, nil, class: "form-control"  %>
    </div>
    <div class="small">
      <p><b>Format text:</b></p>
      <p>For <b>bold text: </b> wrap text between two **<br>
      <u>example:</u> **<b>my bold text</b>**</p>
      <p>For bullet points: start your line with one *
      <br><u>example:</u><br>
      * first bullet point<br>
      * second bullet point</p>
    </div>
    <hr>
    <div class="form-group">
      <%= label_tag  :published, "Published" %>
      <%= check_box_tag :published, true, class: "form-control"  %>
    </div>
    <h5>Variations</h5>
    <div class="form-group text-center" id="product-type-container">
      <%= label_tag  :product_type_with_colors, "PRODUCT WITH COLOR VARIATIONS", class: 'btn btn-dark-gray small', id: 'product-with-color' %>
      <%= radio_button_tag 'product_type', 'with_colors', false, class: "display-none"  %>
      <%= label_tag  :product_type_without_colors, "PRODUCT WITHOUT COLOR VARIATIONS", class: 'btn btn-dark-gray small', id: 'product-without-color' %>
      <%= radio_button_tag 'product_type', 'without_colors', false, class: "display-none"  %>
    </div>
    <div class="product-without-color display-none">
      <div class="color-element" data-id='0'>
        <div class="form-group">
          <%= hidden_field_tag "color_variations[][color]", 'unique' %>
        </div>
        <div class="size-variations">
          <div class="size-element" data-id='0'>
            <div class="form-group">
              <%= label_tag  :size, "Size" %>
              <%= text_field_tag 'color_variations[][size_variations][][size]', nil, class: "form-control"  %>
              <small class="form-text text-muted">Put 'unique' for unique sizes</small>
            </div>
            <div class="form-group">
              <%= label_tag  :price, "Price" %>
              <%= number_field_tag 'color_variations[][size_variations][][price]', nil, step: 0.01, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%= label_tag  :discount_price, "Discount Price" %>
              <%= number_field_tag 'color_variations[][size_variations][][discount_price]', nil,  step: 0.01, class: "form-control"  %>
            </div>
            <div class="form-group">
              <%= label_tag  :quantity, "Quantity" %>
              <%= text_field_tag 'color_variations[][size_variations][][quantity]', nil, class: "form-control"  %>
            </div>
          </div>
        </div>
        <span class="btn btn-dark-gray small add-element" data-id='0' data-type="size">Add Size</span>
        <hr>
        <div class="product-photos">
          <div class="photo-element" data-id='0'>
            <div class="form-group">
              <%= label_tag  :photo, "Photo" %>
              <%= file_field_tag 'color_variations[][photos][][photo]' %>
            </div>
            <div class="form-group">
              <%= label_tag  :main_photo, "Main Photo?" %>
              <%= radio_button_tag 'color_variations[][photos][][main]', true %>
            </div>
          </div>
        </div>
        <span class="btn btn-dark-gray small add-element" data-id='0' data-type="photo">Add Photo</span>
      </div>
    </div>

    <div class="product-with-color display-none">
      <div class="color-variations">
        <div class="color-element" data-id='1'>
          <div class="form-group">
            <%= select_tag "color_variations[][color]", raw(@colors), class: 'form-control'%>
          </div>
          <div class="size-variations">
            <div class="size-element" data-id='1'>
              <div class="form-group">
                <%= label_tag  :size, "Size" %>
                <%= text_field_tag 'color_variations[][size_variations][][size]', nil, class: "form-control"  %>
                <small class="form-text text-muted">Put 'unique' for unique sizes</small>
              </div>
              <div class="form-group">
                <%= label_tag  :price, "Price" %>
                <%= number_field_tag 'color_variations[][size_variations][][price]', nil, step: 0.01, class: "form-control"  %>
              </div>
              <div class="form-group">
                <%= label_tag  :discount_price, "Discount Price" %>
                <%= number_field_tag 'color_variations[][size_variations][][discount_price]', nil, step: 0.01, class: "form-control"  %>
              </div>
              <div class="form-group">
                <%= label_tag  :quantity, "Quantity" %>
                <%= text_field_tag 'color_variations[][size_variations][][quantity]', nil, class: "form-control"  %>
              </div>
            </div>
          </div>
          <span class="btn btn-dark-gray small add-element" data-id='1' data-type='size'>Add Size</span>
          <hr>
          <div class="product-photos">
            <div class="photo-element" data-id='1'>
              <div class="form-group">
                <%= label_tag  :photo, "Photo" %>
                <%= file_field_tag 'color_variations[][photos][][photo]' %>
              </div>
              <div class="form-group">
                <%= label_tag  :main_photo, "Main Photo?" %>
                <%= radio_button_tag 'color_variations[][photos][][main]', true %>
              </div>
            </div>
          </div>
          <span class="btn btn-dark-gray small add-element" data-id='1' data-type='photo'>Add Photo</span>
        </div>
      </div>
      <span class="btn btn-dark-gray small add-element" data-type='color'>Add Color</span>
    </div>
    <%= submit_tag 'CREATE PRODUCT', class: 'btn btn-blue w-100', id: 'create-product' %>
  <% end %>
</div>